name: Build and Publish Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # .NET SDK

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build .NET MAUI project
      run: dotnet build -t:restore -t:build --configuration Release --framework net8.0-android

    - name: Move APK file to Android project directory
      run: mv bin/Release/net8.0-android/*.apk Platforms/Android
