name: Get Backlog board views

on:
  issues:
    types: [opened]

jobs:
  get_board_views:
    runs-on: ubuntu-latest
    steps:
      - name: Get Backlog board views
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          project_id=3  # Замените на реальный ID проекта "WitcherTPRG"
          board_id=1    # Замените на реальный ID доски "Backlog"
          
          # Получаем список представлений в доске "Backlog"
          views=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/$project_id/boards/$board_id/views" | jq '.[] | .name')
          
          echo "Views in board 'Backlog' (project 'WitcherTPRG'):"
          echo "$views"
