name: Get Backlog board ID

on:
  issues:
    types: [opened]

jobs:
  get_board_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Backlog board ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          project_id=3  # Замените на реальный ID проекта "WitcherTPRG"
          board_name="Backlog"

          # Получаем список досок в проекте
          boards=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/3/views")

          # Находим ID доски "Backlog" в списке досок
          board_id=$(echo "$boards" | jq -r '.[] | select(.name == "'"$board_name"'") | .id')
          
          if [ -z "$board_id" ]; then
            echo "Board '$board_name' not found in project 'WitcherTPRG'."
          else
            echo "Board ID for '$board_name' in project 'WitcherTPRG' is $board_id."
          fi
