name: Get Backlog board views

on:
  push:
    branches:
      - master

jobs:
  get_board_views:
    runs-on: ubuntu-latest
    steps:
      - name: Get Backlog board views
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: 3  # Замените на реальный ID проекта "WitcherTPRG"
          BOARD_ID: 1    # Замените на реальный ID доски "Backlog"
        run: |
          views=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/$PROJECT_ID/boards/$BOARD_ID/views" | jq '.[] | .name')
          echo "::set-output name=response::$views"  # Сохраняем ответ в выходную переменную

      - name: Check for error
        id: check_error
        run: echo "${{ steps.get_board_views.outputs.response }}" | jq '.error'  # Проверяем наличие ошибки в ответе

      - name: Handle Error
        if: steps.check_error.outputs.error
        run: |
          error_message=$(echo "${{ steps.get_board_views.outputs.response }}" | jq -r '.error.message')
          echo "Error occurred: $error_message"
          curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "1000000000", "text": "Я не сделяль $error_message"}' https://api.telegram.org/bot100000000000:AAaaaaaaaaaaaaaaa/sendMessage
          
      - name: Handle Success
        if: steps.check_error.outputs.error == null
        run: |
          echo "No error detected"
          curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "100000", "text": "Я сделяль $GITHUB_WORKFLOW"}' https://api.telegram.org/bot1000000:AAaaaaaaaaaaaaaaaaa/sendMessage
