name: Find WitcherTPRG project ID

on:
  issues:
    types: [opened]

jobs:
  find_project_id:
    runs-on: ubuntu-latest
    steps:
      - name: Find WitcherTPRG project ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          project_name="WitcherTPRG"
          project_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/projects" | jq -r ".[] | select(.name == \"$project_name\") | .id")
          if [ -z "$project_id" ]; then
            echo "Project '$project_name' not found."
            exit 1
          fi
          echo "Project ID for '$project_name' is $project_id."
