name: Get Backlog board views

on:
  push:
    branches:
      - master

jobs:
  get_board_views:
    runs-on: ubuntu-latest
    steps:
      - name: Get Backlog board views
        id: hello
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: 3  # Замените на реальный ID проекта "WitcherTPRG"
          BOARD_ID: 1    # Замените на реальный ID доски "Backlog"
        run: |
          views=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/$PROJECT_ID/boards/$BOARD_ID/views" | jq '.[] | .name')
          curl_exit_code=$?
          if [ $curl_exit_code -ne 0 ]; then
            echo "Ошибка при выполнении команды curl"
          exit 1
          fi
            echo "Команда curl выполнена успешно"
  check_job_status:
    needs: get_board_views
    runs-on: ubuntu-latest
    steps:
      - name: Check if the previous job failed
        if: ${{ failure() }}
        run: |
          echo "Предыдущий джоб завершился с ошибкой"
      
      - name: Check if the previous job succeeded
        if: ${{ success() }}
        run: |
          echo "Предыдущий джоб завершился успешно"
