name: Move issue to WitcherTPRG project

on:
  issues:
    types: [opened]

jobs:
  move_to_witcher_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to WitcherTPRG project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          project_id=3  # Замените на реальный ID проекта "WitcherTPRG"
          board_name="Backlog"
          status_name="Todo"

          # Найти ID доски
          board_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/$project_id/boards" | jq -r '.[] | select(.name == "'$board_name'") | .id')
          
          if [ -z "$board_id" ]; then
            echo "Board '$board_name' not found in project 'WitcherTPRG'."
            exit 1
          fi
          
          # Найти ID колонки "Todo" в доске "Backlog"
          status_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/columns/$board_id/cards" | jq -r '.[] | select(.note == "'$status_name'") | .id')
          
          if [ -z "$status_id" ]; then
            echo "Status '$status_name' not found in board '$board_name' in project 'WitcherTPRG'."
            exit 1
          fi
          
          # Переместить задачу в колонку "Todo"
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" -d "{\"content_id\": $issue_number}" "https://api.github.com/projects/columns/cards/$status_id/moves"
