name: Get Backlog board ID

on:
  workflow_dispatch:

jobs:
  get_board_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Backlog board ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          project_id=3  # Замените на реальный ID проекта "WitcherTPRG"
          board_name="Backlog"

          # Найти ID доски "Backlog" в проекте "WitcherTPRG"
          board_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/projects/$project_id/boards" | jq -r '.[] | select(.name == "'$board_name'") | .id')
          
          if [ -z "$board_id" ]; then
            echo "Board '$board_name' not found in project 'WitcherTPRG'."
          else
            echo "Board ID for '$board_name' in project 'WitcherTPRG' is $board_id."
          fi
